name: Add issues/PRs to the TechDev project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

permissions: read-all

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: add to TechDev project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/CCBR/projects/17
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
      - name: add to MOSuite project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/CCBR/projects/32
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
